name:                haskell-solutions
version:             0.1.0.0
github:              "githubuser/haskell-solutions"
license:             BSD3
author:              "Nathan Flynn"
copyright:           "2019 Nathan Flynn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-solutions#readme>

dependencies:
- base >= 4.7 && < 5
- split

library:
  source-dirs: src

executables:
  haskell-solutions-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-solutions

tests:
  haskell-solutions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-solutions
